spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 580473374375-d7gm5u312u0857ot8qhu2p066jsfc1q9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: asdfdfasddsgsaf13241324fdsfdssdgsdgfasdfasdf432351234
  access-token-expire-time: 10000
  refresh-token-expire-time: 2592000  # 30 days 7776000000