spring:
  jpa:
    hibernate:
      ddl-auto: update #create
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 580473374375-d7gm5u312u0857ot8qhu2p066jsfc1q9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  # "openssl rand -hex 64"
  secret: f463969042c515804e2071a5954d0686444dadc5b9d5d90715ab35c0e947211d94bb1b08f15a2a4842cf21a05a4e1e2f00c7cb66624612fde9e0f31bc8000c9e
  access-token-expire-time: 500     # 1000 == 1 second
  refresh-token-expire-time: 1000000