spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  data:
#    redis:
#      host: localhost
#      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(xxQW/5mJYvEtk7wdQRmSewgHK3cVkAd2gzLRJsCphF3c4SX+LPqBWcXZNrnXkSIGus31ynLFz4K4hXm+17gkmsXv42aMPDrxyh9ao1vVHpU=)
            client-secret: ENC(+cAQeKkMGXceLt+tQWIKflwejlcnnOInLeUH+TftLzop+sty6tQ4Na3J9vz3cMH7)
            scope:
              - profile
              - email


jwt:
  secret: ENC(SeSHiBANLVAP2N+yK65oyVlJa5xxxlAyDQYy7mkbyQq1+sNIDXyqPoN/o8/WpNqKzU/9Ez13N0F7GhFNv/+GZszKjaCm4nekDTehoh/woCe6e8/w5E8Ifv4EL/e0xmZoRfAJL3wx7ZEjGEYaPeCVNYzQ/YMHycix01UmHA63S19YUeyPId/GtELnOJl65OfF)
  access-token-expire-time: 20000     # 1000 == 1 second
  refresh-token-expire-time: 50000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor